### ISSUE TITLE
Can't specify a vendorId when creating a Quote

### ISSUE THREAD

**Issue by sgalway00** [invoiceninja/flutter-package#6]
Trying to run the following code:

```
  Future<void> createNewQuote(InvoiceNinjaClient invoiceClient) async {
   

    Product product = = await InvoiceNinja.products.findByKey("myProductKey");

    Client client = await InvoiceNinjaAdmin.clients.findByEmail(invoiceClient.email).timeout(Duration(seconds: 30));

    print('Client retrieved');

    Quote quote = Quote.forClient(client, products: [product]);

    print('Ready to send quote');

    await InvoiceNinjaAdmin.quotes.save(quote);
    print('Quote sent to invoice Ninja');
  }
```
results in the following error:

`package:invoiceninja/models/quote.freezed.dart': Failed assertion: line 795 pos 16: 'vendorId != null': is not true.`

I cannot figure out how to specify the vendorId for the Quote.  Creating an invoice works fine, this only appears when creating a quote.

**Comment by hillelcoren** [comment]
Hi,

Thanks for reporting this, I'll look into it...

**Comment by hillelcoren** [comment]
Have you enabled null safety in your app? It isn't yet supported by the package but we plan to work on it.

**Comment by hillelcoren** [comment]
We've deployed a new version of the package (0.0.9), when you have a chance can you please try again?

**Comment by sgalway00** [comment]
My apologies for the delay.  The latest version has a version solving error with http and firebase.

```
Because invoiceninja >=0.0.9 depends on http ^0.13.1 and carlinehound depends on http ^0.12.2, invoiceninja >=0.0.9 is forbidden.
So, because carlinehound depends on invoiceninja ^0.0.9, version solving failed.
```

If I upgrade to http 0.13.1 I will get the following conflict with firebase:

`Because http >=0.13.0 depends on http_parser ^4.0.0 and firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, http >=0.13.0 is incompatible with firebase >=7.0.0 <9.0.0.`

**Comment by hillelcoren** [comment]
Sorry, I'm not sure I can help with the error.

**Comment by hillelcoren** [comment]
This article may help: https://iiro.dev/resolving-dart-package-version-conflicts/
