### ISSUE TITLE
Auto send email when invoice is created

### ISSUE THREAD

**Issue by sgalway00** [invoiceninja/flutter-package#8]
I would appreciate the ability to auto send an email with a newly created invoice (or link to payment portal).

**Comment by erperejildo** [comment]
is this project abandoned?

**Comment by hillelcoren** [comment]
No, we've just been busy working on the main app

**Comment by hillelcoren** [comment]
In the next release we've added an optional `action` parameter. 

For invoices the options are: send email, mark sent, mark paid and auto bill.
